export type PersonCategory =
  | 'entertainment'
  | 'sports'
  | 'politics'
  | 'science_tech'
  | 'media_culture';

export interface SeedPerson {
  wikidataQid: string;
  displayName: string;
  wikipediaTitle: string;
  category: PersonCategory;
}

export const SEED_REGISTRY: SeedPerson[] = [
  // ── Entertainment: Music ─────────────────────────────────────────────────
  { wikidataQid: 'Q26876', displayName: 'Taylor Swift', wikipediaTitle: 'Taylor_Swift', category: 'entertainment' },
  { wikidataQid: 'Q430', displayName: 'Beyoncé', wikipediaTitle: 'Beyoncé', category: 'entertainment' },
  { wikidataQid: 'Q1373', displayName: 'Rihanna', wikipediaTitle: 'Rihanna', category: 'entertainment' },
  { wikidataQid: 'Q41254', displayName: 'Lady Gaga', wikipediaTitle: 'Lady_Gaga', category: 'entertainment' },
  { wikidataQid: 'Q19975', displayName: 'Adele', wikipediaTitle: 'Adele', category: 'entertainment' },
  { wikidataQid: 'Q2657718', displayName: 'Justin Bieber', wikipediaTitle: 'Justin_Bieber', category: 'entertainment' },
  { wikidataQid: 'Q1699583', displayName: 'Ariana Grande', wikipediaTitle: 'Ariana_Grande', category: 'entertainment' },
  { wikidataQid: 'Q33483', displayName: 'Drake', wikipediaTitle: 'Drake_(musician)', category: 'entertainment' },
  { wikidataQid: 'Q169452', displayName: 'Kanye West', wikipediaTitle: 'Kanye_West', category: 'entertainment' },
  { wikidataQid: 'Q2164386', displayName: 'Kendrick Lamar', wikipediaTitle: 'Kendrick_Lamar', category: 'entertainment' },
  { wikidataQid: 'Q1406278', displayName: 'Ed Sheeran', wikipediaTitle: 'Ed_Sheeran', category: 'entertainment' },
  { wikidataQid: 'Q47898036', displayName: 'Billie Eilish', wikipediaTitle: 'Billie_Eilish', category: 'entertainment' },
  { wikidataQid: 'Q2140539', displayName: 'The Weeknd', wikipediaTitle: 'The_Weeknd', category: 'entertainment' },
  { wikidataQid: 'Q1168897', displayName: 'Bruno Mars', wikipediaTitle: 'Bruno_Mars', category: 'entertainment' },
  { wikidataQid: 'Q16742479', displayName: 'Dua Lipa', wikipediaTitle: 'Dua_Lipa', category: 'entertainment' },
  { wikidataQid: 'Q27991676', displayName: 'Post Malone', wikipediaTitle: 'Post_Malone', category: 'entertainment' },
  { wikidataQid: 'Q488864', displayName: 'Nicki Minaj', wikipediaTitle: 'Nicki_Minaj', category: 'entertainment' },
  { wikidataQid: 'Q37671473', displayName: 'Cardi B', wikipediaTitle: 'Cardi_B', category: 'entertainment' },
  { wikidataQid: 'Q18617643', displayName: 'Doja Cat', wikipediaTitle: 'Doja_Cat', category: 'entertainment' },
  { wikidataQid: 'Q17741069', displayName: 'Harry Styles', wikipediaTitle: 'Harry_Styles', category: 'entertainment' },
  { wikidataQid: 'Q92256952', displayName: 'Olivia Rodrigo', wikipediaTitle: 'Olivia_Rodrigo', category: 'entertainment' },
  { wikidataQid: 'Q25348272', displayName: 'Bad Bunny', wikipediaTitle: 'Bad_Bunny', category: 'entertainment' },
  { wikidataQid: 'Q1935', displayName: 'Eminem', wikipediaTitle: 'Eminem', category: 'entertainment' },
  { wikidataQid: 'Q140547', displayName: 'Jay-Z', wikipediaTitle: 'Jay-Z', category: 'entertainment' },
  { wikidataQid: 'Q494703', displayName: 'BTS', wikipediaTitle: 'BTS_(band)', category: 'entertainment' },
  { wikidataQid: 'Q16245490', displayName: 'BLACKPINK', wikipediaTitle: 'Blackpink', category: 'entertainment' },
  // ── Entertainment: Film/TV ────────────────────────────────────────────────
  { wikidataQid: 'Q2263', displayName: 'Tom Hanks', wikipediaTitle: 'Tom_Hanks', category: 'entertainment' },
  { wikidataQid: 'Q873', displayName: 'Meryl Streep', wikipediaTitle: 'Meryl_Streep', category: 'entertainment' },
  { wikidataQid: 'Q38111', displayName: 'Leonardo DiCaprio', wikipediaTitle: 'Leonardo_DiCaprio', category: 'entertainment' },
  { wikidataQid: 'Q34851', displayName: 'Scarlett Johansson', wikipediaTitle: 'Scarlett_Johansson', category: 'entertainment' },
  { wikidataQid: 'Q35332', displayName: 'Brad Pitt', wikipediaTitle: 'Brad_Pitt', category: 'entertainment' },
  { wikidataQid: 'Q13909', displayName: 'Angelina Jolie', wikipediaTitle: 'Angelina_Jolie', category: 'entertainment' },
  { wikidataQid: 'Q91107', displayName: 'Jennifer Lawrence', wikipediaTitle: 'Jennifer_Lawrence', category: 'entertainment' },
  { wikidataQid: 'Q26208', displayName: 'Ryan Reynolds', wikipediaTitle: 'Ryan_Reynolds', category: 'entertainment' },
  { wikidataQid: 'Q44171', displayName: 'Dwayne Johnson', wikipediaTitle: 'Dwayne_Johnson', category: 'entertainment' },
  { wikidataQid: 'Q11706025', displayName: 'Zendaya', wikipediaTitle: 'Zendaya', category: 'entertainment' },
  { wikidataQid: 'Q229223', displayName: 'Margot Robbie', wikipediaTitle: 'Margot_Robbie', category: 'entertainment' },
  { wikidataQid: 'Q189811', displayName: 'Chris Hemsworth', wikipediaTitle: 'Chris_Hemsworth', category: 'entertainment' },
  { wikidataQid: 'Q33556', displayName: 'Robert Downey Jr.', wikipediaTitle: 'Robert_Downey_Jr.', category: 'entertainment' },
  { wikidataQid: 'Q81506', displayName: 'Emma Stone', wikipediaTitle: 'Emma_Stone', category: 'entertainment' },
  // ── Sports ────────────────────────────────────────────────────────────────
  { wikidataQid: 'Q36159', displayName: 'LeBron James', wikipediaTitle: 'LeBron_James', category: 'sports' },
  { wikidataQid: 'Q11571', displayName: 'Cristiano Ronaldo', wikipediaTitle: 'Cristiano_Ronaldo', category: 'sports' },
  { wikidataQid: 'Q615', displayName: 'Lionel Messi', wikipediaTitle: 'Lionel_Messi', category: 'sports' },
  { wikidataQid: 'Q11830', displayName: 'Serena Williams', wikipediaTitle: 'Serena_Williams', category: 'sports' },
  { wikidataQid: 'Q1426', displayName: 'Roger Federer', wikipediaTitle: 'Roger_Federer', category: 'sports' },
  { wikidataQid: 'Q10132', displayName: 'Rafael Nadal', wikipediaTitle: 'Rafael_Nadal', category: 'sports' },
  { wikidataQid: 'Q1652', displayName: 'Novak Djokovic', wikipediaTitle: 'Novak_Djokovic', category: 'sports' },
  { wikidataQid: 'Q27964', displayName: 'Tiger Woods', wikipediaTitle: 'Tiger_Woods', category: 'sports' },
  { wikidataQid: 'Q41421', displayName: 'Michael Jordan', wikipediaTitle: 'Michael_Jordan', category: 'sports' },
  { wikidataQid: 'Q352525', displayName: 'Stephen Curry', wikipediaTitle: 'Stephen_Curry', category: 'sports' },
  { wikidataQid: 'Q706346', displayName: 'Kevin Durant', wikipediaTitle: 'Kevin_Durant', category: 'sports' },
  { wikidataQid: 'Q23040892', displayName: 'Simone Biles', wikipediaTitle: 'Simone_Biles', category: 'sports' },
  { wikidataQid: 'Q22688920', displayName: 'Naomi Osaka', wikipediaTitle: 'Naomi_Osaka', category: 'sports' },
  { wikidataQid: 'Q1189989', displayName: 'Usain Bolt', wikipediaTitle: 'Usain_Bolt', category: 'sports' },
  { wikidataQid: 'Q82466', displayName: 'Michael Phelps', wikipediaTitle: 'Michael_Phelps', category: 'sports' },
  { wikidataQid: 'Q9673', displayName: 'Lewis Hamilton', wikipediaTitle: 'Lewis_Hamilton', category: 'sports' },
  { wikidataQid: 'Q1189970', displayName: 'Kylian Mbappé', wikipediaTitle: 'Kylian_Mbappé', category: 'sports' },
  { wikidataQid: 'Q194948', displayName: 'Neymar', wikipediaTitle: 'Neymar', category: 'sports' },
  { wikidataQid: 'Q314879', displayName: 'Mohamed Salah', wikipediaTitle: 'Mohamed_Salah', category: 'sports' },
  { wikidataQid: 'Q1386117', displayName: 'Virat Kohli', wikipediaTitle: 'Virat_Kohli', category: 'sports' },
  { wikidataQid: 'Q6513306', displayName: 'Conor McGregor', wikipediaTitle: 'Conor_McGregor', category: 'sports' },
  { wikidataQid: 'Q232013', displayName: 'Tom Brady', wikipediaTitle: 'Tom_Brady', category: 'sports' },
  { wikidataQid: 'Q24032093', displayName: 'Patrick Mahomes', wikipediaTitle: 'Patrick_Mahomes', category: 'sports' },
  { wikidataQid: 'Q116823754', displayName: 'Caitlin Clark', wikipediaTitle: 'Caitlin_Clark', category: 'sports' },
  { wikidataQid: 'Q15873855', displayName: 'Giannis Antetokounmpo', wikipediaTitle: 'Giannis_Antetokounmpo', category: 'sports' },
  { wikidataQid: 'Q159712', displayName: 'Sebastian Vettel', wikipediaTitle: 'Sebastian_Vettel', category: 'sports' },
  { wikidataQid: 'Q1087756', displayName: 'Saúl Álvarez', wikipediaTitle: 'Canelo_Álvarez', category: 'sports' },
  { wikidataQid: 'Q64137155', displayName: "Sha'Carri Richardson", wikipediaTitle: "Sha'Carri_Richardson", category: 'sports' },
  // ── Politics / World Leaders ──────────────────────────────────────────────
  { wikidataQid: 'Q76', displayName: 'Barack Obama', wikipediaTitle: 'Barack_Obama', category: 'politics' },
  { wikidataQid: 'Q6279', displayName: 'Joe Biden', wikipediaTitle: 'Joe_Biden', category: 'politics' },
  { wikidataQid: 'Q22686', displayName: 'Donald Trump', wikipediaTitle: 'Donald_Trump', category: 'politics' },
  { wikidataQid: 'Q3052772', displayName: 'Emmanuel Macron', wikipediaTitle: 'Emmanuel_Macron', category: 'politics' },
  { wikidataQid: 'Q7747', displayName: 'Vladimir Putin', wikipediaTitle: 'Vladimir_Putin', category: 'politics' },
  { wikidataQid: 'Q567', displayName: 'Angela Merkel', wikipediaTitle: 'Angela_Merkel', category: 'politics' },
  { wikidataQid: 'Q34263', displayName: 'Xi Jinping', wikipediaTitle: 'Xi_Jinping', category: 'politics' },
  { wikidataQid: 'Q1058098', displayName: 'Narendra Modi', wikipediaTitle: 'Narendra_Modi', category: 'politics' },
  { wikidataQid: 'Q180589', displayName: 'Boris Johnson', wikipediaTitle: 'Boris_Johnson', category: 'politics' },
  { wikidataQid: 'Q3099714', displayName: 'Justin Trudeau', wikipediaTitle: 'Justin_Trudeau', category: 'politics' },
  { wikidataQid: 'Q320274', displayName: 'Jacinda Ardern', wikipediaTitle: 'Jacinda_Ardern', category: 'politics' },
  { wikidataQid: 'Q14140132', displayName: 'Volodymyr Zelensky', wikipediaTitle: 'Volodymyr_Zelensky', category: 'politics' },
  { wikidataQid: 'Q6294', displayName: 'Kamala Harris', wikipediaTitle: 'Kamala_Harris', category: 'politics' },
  { wikidataQid: 'Q55223036', displayName: 'Alexandria Ocasio-Cortez', wikipediaTitle: 'Alexandria_Ocasio-Cortez', category: 'politics' },
  { wikidataQid: 'Q184746', displayName: 'Malala Yousafzai', wikipediaTitle: 'Malala_Yousafzai', category: 'politics' },
  { wikidataQid: 'Q6888339', displayName: 'Greta Thunberg', wikipediaTitle: 'Greta_Thunberg', category: 'politics' },
  { wikidataQid: 'Q450675', displayName: 'Pope Francis', wikipediaTitle: 'Pope_Francis', category: 'politics' },
  { wikidataQid: 'Q359442', displayName: 'Bernie Sanders', wikipediaTitle: 'Bernie_Sanders', category: 'politics' },
  { wikidataQid: 'Q170581', displayName: 'Nancy Pelosi', wikipediaTitle: 'Nancy_Pelosi', category: 'politics' },
  { wikidataQid: 'Q58219', displayName: 'Jair Bolsonaro', wikipediaTitle: 'Jair_Bolsonaro', category: 'politics' },
  // ── Science & Technology ──────────────────────────────────────────────────
  { wikidataQid: 'Q5284', displayName: 'Bill Gates', wikipediaTitle: 'Bill_Gates', category: 'science_tech' },
  { wikidataQid: 'Q549934', displayName: 'Tim Cook', wikipediaTitle: 'Tim_Cook', category: 'science_tech' },
  { wikidataQid: 'Q6281', displayName: 'Mark Zuckerberg', wikipediaTitle: 'Mark_Zuckerberg', category: 'science_tech' },
  { wikidataQid: 'Q312', displayName: 'Jeff Bezos', wikipediaTitle: 'Jeff_Bezos', category: 'science_tech' },
  { wikidataQid: 'Q317521', displayName: 'Elon Musk', wikipediaTitle: 'Elon_Musk', category: 'politics' },
  { wikidataQid: 'Q1014285', displayName: 'Sundar Pichai', wikipediaTitle: 'Sundar_Pichai', category: 'science_tech' },
  { wikidataQid: 'Q14358432', displayName: 'Satya Nadella', wikipediaTitle: 'Satya_Nadella', category: 'science_tech' },
  { wikidataQid: 'Q85399688', displayName: 'Sam Altman', wikipediaTitle: 'Sam_Altman', category: 'science_tech' },
  { wikidataQid: 'Q15803439', displayName: 'Jensen Huang', wikipediaTitle: 'Jensen_Huang', category: 'science_tech' },
  { wikidataQid: 'Q9695', displayName: 'Stephen Hawking', wikipediaTitle: 'Stephen_Hawking', category: 'science_tech' },
  { wikidataQid: 'Q392462', displayName: 'Neil deGrasse Tyson', wikipediaTitle: 'Neil_deGrasse_Tyson', category: 'science_tech' },
  { wikidataQid: 'Q51660', displayName: 'Jane Goodall', wikipediaTitle: 'Jane_Goodall', category: 'science_tech' },
  { wikidataQid: 'Q177565', displayName: 'Richard Dawkins', wikipediaTitle: 'Richard_Dawkins', category: 'science_tech' },
  { wikidataQid: 'Q1339864', displayName: 'Yuval Noah Harari', wikipediaTitle: 'Yuval_Noah_Harari', category: 'science_tech' },
  { wikidataQid: 'Q19837', displayName: 'Steve Jobs', wikipediaTitle: 'Steve_Jobs', category: 'science_tech' },
  { wikidataQid: 'Q2624061', displayName: 'Larry Page', wikipediaTitle: 'Larry_Page', category: 'science_tech' },
  { wikidataQid: 'Q20903', displayName: 'Sergey Brin', wikipediaTitle: 'Sergey_Brin', category: 'science_tech' },
  { wikidataQid: 'Q92743', displayName: 'Jack Dorsey', wikipediaTitle: 'Jack_Dorsey', category: 'science_tech' },
  // ── Media & Culture ───────────────────────────────────────────────────────
  { wikidataQid: 'Q55800', displayName: 'Oprah Winfrey', wikipediaTitle: 'Oprah_Winfrey', category: 'media_culture' },
  { wikidataQid: 'Q36537415', displayName: 'MrBeast', wikipediaTitle: 'MrBeast', category: 'media_culture' },
  { wikidataQid: 'Q92405', displayName: 'PewDiePie', wikipediaTitle: 'PewDiePie', category: 'media_culture' },
  { wikidataQid: 'Q1985706', displayName: 'Joe Rogan', wikipediaTitle: 'Joe_Rogan', category: 'media_culture' },
  { wikidataQid: 'Q178734', displayName: 'Howard Stern', wikipediaTitle: 'Howard_Stern', category: 'media_culture' },
  { wikidataQid: 'Q230552', displayName: 'Ellen DeGeneres', wikipediaTitle: 'Ellen_DeGeneres', category: 'media_culture' },
  { wikidataQid: 'Q313039', displayName: 'Jimmy Fallon', wikipediaTitle: 'Jimmy_Fallon', category: 'media_culture' },
  { wikidataQid: 'Q312836', displayName: 'Stephen Colbert', wikipediaTitle: 'Stephen_Colbert', category: 'media_culture' },
  { wikidataQid: 'Q7839153', displayName: 'Trevor Noah', wikipediaTitle: 'Trevor_Noah', category: 'media_culture' },
  { wikidataQid: 'Q186304', displayName: 'Kim Kardashian', wikipediaTitle: 'Kim_Kardashian', category: 'media_culture' },
  { wikidataQid: 'Q17463049', displayName: 'Kylie Jenner', wikipediaTitle: 'Kylie_Jenner', category: 'media_culture' },
  { wikidataQid: 'Q17440946', displayName: 'Kendall Jenner', wikipediaTitle: 'Kendall_Jenner', category: 'media_culture' },
  { wikidataQid: 'Q47160', displayName: 'Paris Hilton', wikipediaTitle: 'Paris_Hilton', category: 'media_culture' },
  { wikidataQid: 'Q313424', displayName: 'Ryan Seacrest', wikipediaTitle: 'Ryan_Seacrest', category: 'media_culture' },
  { wikidataQid: 'Q1029070', displayName: 'James Corden', wikipediaTitle: 'James_Corden', category: 'media_culture' },
  { wikidataQid: 'Q232003', displayName: 'Graham Norton', wikipediaTitle: 'Graham_Norton', category: 'media_culture' },
  { wikidataQid: 'Q5588', displayName: 'Gordon Ramsay', wikipediaTitle: 'Gordon_Ramsay', category: 'media_culture' },
  { wikidataQid: 'Q3098956', displayName: 'Chrissy Teigen', wikipediaTitle: 'Chrissy_Teigen', category: 'media_culture' },
  { wikidataQid: 'Q1048730', displayName: 'John Oliver', wikipediaTitle: 'John_Oliver', category: 'media_culture' },
  { wikidataQid: 'Q272004', displayName: 'Dave Chappelle', wikipediaTitle: 'Dave_Chappelle', category: 'media_culture' },
  { wikidataQid: 'Q313358', displayName: 'Jimmy Kimmel', wikipediaTitle: 'Jimmy_Kimmel', category: 'media_culture' },
  { wikidataQid: 'Q458876', displayName: 'Seth Meyers', wikipediaTitle: 'Seth_Meyers', category: 'media_culture' },
  { wikidataQid: 'Q188792', displayName: 'Conan O\'Brien', wikipediaTitle: 'Conan_O\'Brien', category: 'media_culture' },
];
